import tosca, tosca.datatypes
	
class NetworkInfo(tosca.datatypes.Root):
	"""
	The Network type is a complex TOSCA data type used to describe logical network information.
	
	`TOSCA Simple Profile v1.0 <http://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.0/csprd02/TOSCA-Simple-Profile-YAML-v1.0-csprd02.html#TYPE_TOSCA_DATA_NETWORKINFO>`
	"""
	
	DESCRIPTION = 'The Network type is a complex TOSCA data type used to describe logical network information.'

	SHORTHAND_NAME = 'NetworkInfo'
	TYPE_QUALIFIED_NAME = 'tosca:NetworkInfo'
	TYPE_URI = 'tosca.datatypes.network.NetworkInfo'
	
	PROPERTIES = {
		'network_name': {'type': str, 'description': 'The name of the logical network. e.g., "public", "private", "admin". etc.'},
		'network_id': {'type': str, 'description': 'The unique ID of for the network generated by the network provider.'},
		'addresses': {'type': tosca.List(str), description: 'The list of IP addresses assigned from the underlying network.'}}
	
class PortInfo(tosca.datatypes.Root):
	"""
	The PortInfo type is a complex TOSCA data type used to describe network port information.
	
	`TOSCA Simple Profile v1.0 <http://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.0/csprd02/TOSCA-Simple-Profile-YAML-v1.0-csprd02.html#TYPE_TOSCA_DATA_PORTINFO>`
	"""
	
	DESCRIPTION = 'The PortInfo type is a complex TOSCA data type used to describe network port information.'

    SHORTHAND_NAME = 'PortInfo'
    TYPE_QUALIFIED_NAME = 'tosca:PortInfo'
    TYPE_URI = 'tosca.datatypes.network.PortInfo'
	
	PROPERTIES = {
		'port_name': {'type': str, 'description': 'The logical network port name.'},
		'port_id': {'type': str, 'description': 'The unique ID for the network port generated by the network provider.'},
		'network_id': {'type': str, 'description': 'The unique ID for the network.'},
		'mac_address': {'type': str, 'description': 'The unique media access control address (MAC address) assigned to the port.'},
		'addresses': {'type': tosca.List(str), 'description': 'The list of IP address(es) assigned to the port.'}}

class PortDef(tosca.Integer):
	"""
	The PortDef type is a TOSCA data Type used to define a network port.
	
	`TOSCA Simple Profile v1.0 <http://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.0/csprd02/TOSCA-Simple-Profile-YAML-v1.0-csprd02.html#TYPE_TOSCA_DATA_PORTDEF>`
	"""
	
	DESCRIPTION = 'The PortDef type is a TOSCA data Type used to define a network port.'

	SHORTHAND_NAME = 'PortDef'
	TYPE_QUALIFIED_NAME = 'tosca:PortDef'
	TYPE_URI = 'tosca.datatypes.network.PortDef'

	CONSTRAINTS = {
		'in_range': {'type': tosca.List(str)}}

class PortSpec(tosca.datatypes.Root):
	"""
	The PortSpec type is a complex TOSCA data Type used when describing port specifications for a network connection.
	
	`TOSCA Simple Profile v1.0 <http://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.0/csprd02/TOSCA-Simple-Profile-YAML-v1.0-csprd02.html#TYPE_TOSCA_DATA_PORTSPEC>`
	"""
	
	DESCRIPTION = 'The PortSpec type is a complex TOSCA data Type used when describing port specifications for a network connection/'

	SHORTHAND_NAME = 'PortSpec'
	TYPE_QUALIFIED_NAME = 'tosca:PortSpec'
	TYPE_URI = 'tosca.datatypes.network.PortSpec'
	
	PROPERTIES = {
		'protocol': {'type': str, 'required': True, 'default': 'tcp', 'description': 'The required protocol used on the port.'},
		'source': {'type': PortDef, 'description': 'The optional source port.'},
		'source_range': {'type': tosca.Range, 'description': 'The optional range for source port.'},
		'target': {'type': PortDef, 'description': 'The optional target port.'},
		'target_range': {'type': tosca.Range, 'description': 'The optional range for target port.'},
